export const FETCH_MOVIE_ACTORS_STARTED = 'FETCH_MOVIE_ACTORS_STARTED'
export const FETCH_MOVIE_ACTORS_COMPLETED = 'FETCH_MOVIE_ACTORS_COMPLETED'
export const FETCH_MOVIE_ACTORS_FAILED = 'FETCH_MOVIE_ACTORS_FAILED'

// ESTOS SI FIJO
export const FETCH_SERIE_ACTORS_STARTED = 'FETCH_SERIE_ACTORS_STARTED'
export const FETCH_SERIE_ACTORS_COMPLETED = 'FETCH_SERIE_ACTORS_COMPLETED'
export const FETCH_SERIE_ACTORS_FAILED = 'FETCH_SERIE_ACTORS_FAILED'

// POR SI DA TIEMPO
export const ADD_MOVIE_ACTORS_STARTED = 'ADD_MOVIE_ACTORS_STARTED'
export const ADD_MOVIE_ACTORS_COMPLETED = 'ADD_MOVIE_ACTORS_COMPLETED'
export const ADD_MOVIE_ACTORS_FAILED = 'ADD_MOVIE_ACTORS_FAILED'
export const REMOVE_MOVIE_ACTORS_STARTED = 'REMOVE_MOVIE_ACTORS_STARTED'
export const REMOVE_MOVIE_ACTORS_COMPLETED = 'REMOVE_MOVIE_ACTORS_COMPLETED'
export const REMOVE_MOVIE_ACTORS_FAILED = 'REMOVE_MOVIE_ACTORS_FAILED'

export const ADD_SERIE_ACTORS_STARTED = 'ADD_SERIE_ACTORS_STARTED'
export const ADD_SERIE_ACTORS_COMPLETED = 'ADD_SERIE_ACTORS_COMPLETED'
export const ADD_SERIE_ACTORS_FAILED = 'ADD_SERIE_ACTORS_FAILED'
export const REMOVE_SERIE_ACTORS_STARTED = 'REMOVE_SERIE_ACTORS_STARTED'
export const REMOVE_SERIE_ACTORS_COMPLETED = 'REMOVE_SERIE_ACTORS_COMPLETED'
export const REMOVE_SERIE_ACTORS_FAILED = 'REMOVE_SERIE_ACTORS_FAILED'
