export const FETCH_MOVIE_AWARDS_STARTED = 'FETCH_MOVIE_AWARDS_STARTED';
export const FETCH_MOVIE_AWARDS_COMPLETED = 'FETCH_MOVIE_AWARDS_COMPLETED';
export const FETCH_MOVIE_AWARDS_FAILED = 'FETCH_MOVIE_AWARDS_FAILED';

export const ADD_MOVIE_AWARD_STARTED = 'ADD_MOVIE_AWARD_STARTED';
export const ADD_MOVIE_AWARD_COMPLETED = 'ADD_MOVIE_AWARD_COMPLETED';
export const ADD_MOVIE_AWARD_FAILED = 'ADD_MOVIE_AWARD_FAILED';

export const REMOVE_MOVIE_AWARD_STARTED = 'REMOVE_MOVIE_AWARD_STARTED';
export const REMOVE_MOVIE_AWARD_COMPLETED = 'REMOVE_MOVIE_AWARD_COMPLETED';
export const REMOVE_MOVIE_AWARD_FAILED = 'REMOVE_MOVIE_AWARD_FAILED';

export const FETCH_SERIE_AWARDS_STARTED = 'FETCH_SERIE_AWARDS_STARTED';
export const FETCH_SERIE_AWARDS_COMPLETED = 'FETCH_SERIE_AWARDS_COMPLETED';
export const FETCH_SERIE_AWARDS_FAILED = 'FETCH_SERIE_AWARDS_FAILED';

export const ADD_SERIE_AWARD_STARTED = 'ADD_SERIE_AWARD_STARTED';
export const ADD_SERIE_AWARD_COMPLETED = 'ADD_SERIE_AWARD_COMPLETED';
export const ADD_SERIE_AWARD_FAILED = 'ADD_SERIE_AWARD_FAILED';

export const REMOVE_SERIE_AWARD_STARTED = 'REMOVE_SERIE_AWARD_STARTED';
export const REMOVE_SERIE_AWARD_COMPLETED = 'REMOVE_SERIE_AWARD_COMPLETED';
export const REMOVE_SERIE_AWARD_FAILED = 'REMOVE_SERIE_AWARD_FAILED';