export const FETCH_AWARDS_STARTED = 'FETCH_AWARDS_STARTED';
export const FETCH_AWARDS_COMPLETED = 'FETCH_AWARDS_COMPLETED';
export const FETCH_AWARDS_FAILED = 'FETCH_AWARDS_FAILED';

export const ADD_AWARD_STARTED = 'ADD_AWARD_STARTED';
export const ADD_AWARD_COMPLETED = 'ADD_AWARD_COMPLETED';
export const ADD_AWARD_FAILED = 'ADD_AWARD_FAILED';

export const REMOVE_AWARD_STARTED = 'REMOVE_AWARD_STARTED';
export const REMOVE_AWARD_COMPLETED = 'REMOVE_AWARD_COMPLETED';
export const REMOVE_AWARD_FAILED = 'REMOVE_AWARD_FAILED';