export const FETCH_MOVIE_COMMENTS_STARTED = 'FETCH_MOVIE_COMMENTS_STARTED';
export const FETCH_MOVIE_COMMENTS_COMPLETED = 'FETCH_MOVIE_COMMENTS_COMPLETED';
export const FETCH_MOVIE_COMMENTS_FAILED = 'FETCH_MOVIE_COMMENTS_FAILED';

export const ADD_MOVIE_COMMENT_STARTED = 'ADD_MOVIE_COMMENT_STARTED';
export const ADD_MOVIE_COMMENT_COMPLETED = 'ADD_MOVIE_COMMENT_COMPLETED';
export const ADD_MOVIE_COMMENT_FAILED = 'ADD_MOVIE_COMMENT_FAILED';

export const REMOVE_MOVIE_COMMENT_STARTED = 'REMOVE_MOVIE_COMMENT_STARTED';
export const REMOVE_MOVIE_COMMENT_COMPLETED = 'REMOVE_MOVIE_COMMENT_COMPLETED';
export const REMOVE_MOVIE_COMMENT_FAILED = 'REMOVE_MOVIE_COMMENT_FAILED';

export const FETCH_SERIE_COMMENTS_STARTED = 'FETCH_SERIE_COMMENTS_STARTED';
export const FETCH_SERIE_COMMENTS_COMPLETED = 'FETCH_SERIE_COMMENTS_COMPLETED';
export const FETCH_SERIE_COMMENTS_FAILED = 'FETCH_SERIE_COMMENTS_FAILED';

export const ADD_SERIE_COMMENT_STARTED = 'ADD_SERIE_COMMENT_STARTED';
export const ADD_SERIE_COMMENT_COMPLETED = 'ADD_SERIE_COMMENT_COMPLETED';
export const ADD_SERIE_COMMENT_FAILED = 'ADD_SERIE_COMMENT_FAILED';

export const REMOVE_SERIE_COMMENT_STARTED = 'REMOVE_SERIE_COMMENT_STARTED';
export const REMOVE_SERIE_COMMENT_COMPLETED = 'REMOVE_SERIE_COMMENT_COMPLETED';
export const REMOVE_SERIE_COMMENT_FAILED = 'REMOVE_SERIE_COMMENT_FAILED';

export const FETCH_GAME_COMMENTS_STARTED = 'FETCH_GAME_COMMENTS_STARTED';
export const FETCH_GAME_COMMENTS_COMPLETED = 'FETCH_GAME_COMMENTS_COMPLETED';
export const FETCH_GAME_COMMENTS_FAILED = 'FETCH_GAME_COMMENTS_FAILED';

export const ADD_GAME_COMMENT_STARTED = 'ADD_GAME_COMMENT_STARTED';
export const ADD_GAME_COMMENT_COMPLETED = 'ADD_GAME_COMMENT_COMPLETED';
export const ADD_GAME_COMMENT_FAILED = 'ADD_GAME_COMMENT_FAILED';

export const REMOVE_GAME_COMMENT_STARTED = 'REMOVE_GAME_COMMENT_STARTED';
export const REMOVE_GAME_COMMENT_COMPLETED = 'REMOVE_GAME_COMMENT_COMPLETED';
export const REMOVE_GAME_COMMENT_FAILED = 'REMOVE_GAME_COMMENT_FAILED';
