export const FETCH_COMMENTS_STARTED = 'FETCH_COMMENTS_STARTED';
export const FETCH_COMMENTS_COMPLETED = 'FETCH_COMMENTS_COMPLETED';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';

export const ADD_COMMENT_STARTED = 'ADD_COMMENT_STARTED';
export const ADD_COMMENT_COMPLETED = 'ADD_COMMENT_COMPLETED';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const REMOVE_COMMENT_STARTED = 'REMOVE_COMMENT_STARTED';
export const REMOVE_COMMENT_COMPLETED = 'REMOVE_COMMENT_COMPLETED';
export const REMOVE_COMMENT_FAILED = 'REMOVE_COMMENT_FAILED';