export const FETCH_CONSOLES_STARTED = 'FETCH_CONSOLES_STARTED';
export const FETCH_CONSOLES_COMPLETED = 'FETCH_CONSOLES_COMPLETED';
export const FETCH_CONSOLES_FAILED = 'FETCH_CONSOLES_FAILED';

export const ADD_CONSOLE_STARTED = 'ADD_CONSOLE_STARTED';
export const ADD_CONSOLE_COMPLETED = 'ADD_CONSOLE_COMPLETED';
export const ADD_CONSOLE_FAILED = 'ADD_CONSOLE_FAILED';

export const REMOVE_CONSOLE_STARTED = 'REMOVE_CONSOLE_STARTED';
export const REMOVE_CONSOLE_COMPLETED = 'REMOVE_CONSOLE_COMPLETED';
export const REMOVE_CONSOLE_FAILED = 'REMOVE_CONSOLE_FAILED';