export const FETCH_DEVELOPERS_STARTED = 'FETCH_DEVELOPERS_STARTED';
export const FETCH_DEVELOPERS_COMPLETED = 'FETCH_DEVELOPERS_COMPLETED';
export const FETCH_DEVELOPERS_FAILED = 'FETCH_DEVELOPERS_FAILED';

export const ADD_DEVELOPER_STARTED = 'ADD_DEVELOPER_STARTED';
export const ADD_DEVELOPER_COMPLETED = 'ADD_DEVELOPER_COMPLETED';
export const ADD_DEVELOPER_FAILED = 'ADD_DEVELOPER_FAILED';

export const REMOVE_DEVELOPER_STARTED = 'REMOVE_DEVELOPER_STARTED';
export const REMOVE_DEVELOPER_COMPLETED = 'REMOVE_DEVELOPER_COMPLETED';
export const REMOVE_DEVELOPER_FAILED = 'REMOVE_DEVELOPER_FAILED';