export const FETCH_DIRECTORS_STARTED = 'FETCH_DIRECTORS_STARTED';
export const FETCH_DIRECTORS_COMPLETED = 'FETCH_DIRECTORS_COMPLETED';
export const FETCH_DIRECTORS_FAILED = 'FETCH_DIRECTORS_FAILED';

export const ADD_DIRECTOR_STARTED = 'ADD_DIRECTOR_STARTED';
export const ADD_DIRECTOR_COMPLETED = 'ADD_DIRECTOR_COMPLETED';
export const ADD_DIRECTOR_FAILED = 'ADD_DIRECTOR_FAILED';

export const REMOVE_DIRECTOR_STARTED = 'REMOVE_DIRECTOR_STARTED';
export const REMOVE_DIRECTOR_COMPLETED = 'REMOVE_DIRECTOR_COMPLETED';
export const REMOVE_DIRECTOR_FAILED = 'REMOVE_DIRECTOR_FAILED';