export const FETCH_SERIE_DIRECTORS_STARTED = 'FETCH_SERIE_DIRECTORS_STARTED';
export const FETCH_SERIE_DIRECTORS_COMPLETED = 'FETCH_SERIE_DIRECTORS_COMPLETED';
export const FETCH_SERIE_DIRECTORS_FAILED = 'FETCH_SERIE_DIRECTORS_FAILED';

export const FETCH_MOVIE_DIRECTORS_STARTED = 'FETCH_MOVIE_DIRECTORS_STARTED';
export const FETCH_MOVIE_DIRECTORS_COMPLETED = 'FETCH_MOVIE_DIRECTORS_COMPLETED';
export const FETCH_MOVIE_DIRECTORS_FAILED = 'FETCH_MOVIE_DIRECTORS_FAILED';

// -----------------------------------
//
//          POR COSTUMBRE 
//
//------------------------------------
export const ADD_SERIE_DIRECTOR_STARTED = 'ADD_SERIE_DIRECTOR_STARTED';
export const ADD_SERIE_DIRECTOR_COMPLETED = 'ADD_SERIE_DIRECTOR_COMPLETED';
export const ADD_SERIE_DIRECTOR_FAILED = 'ADD_SERIE_DIRECTOR_FAILED';

export const REMOVE_SERIE_DIRECTOR_STARTED = 'REMOVE_SERIE_DIRECTOR_STARTED';
export const REMOVE_SERIE_DIRECTOR_COMPLETED = 'REMOVE_SERIE_DIRECTOR_COMPLETED';
export const REMOVE_SERIE_DIRECTOR_FAILED = 'REMOVE_SERIE_DIRECTOR_FAILED';


export const ADD_MOVIE_DIRECTOR_STARTED = 'ADD_MOVIE_DIRECTOR_STARTED';
export const ADD_MOVIE_DIRECTOR_COMPLETED = 'ADD_MOVIE_DIRECTOR_COMPLETED';
export const ADD_MOVIE_DIRECTOR_FAILED = 'ADD_MOVIE_DIRECTOR_FAILED';

export const REMOVE_MOVIE_DIRECTOR_STARTED = 'REMOVE_MOVIE_DIRECTOR_STARTED';
export const REMOVE_MOVIE_DIRECTOR_COMPLETED = 'REMOVE_MOVIE_DIRECTOR_COMPLETED';
export const REMOVE_MOVIE_DIRECTOR_FAILED = 'REMOVE_MOVIE_DIRECTOR_FAILED';