export const FETCH_GENRES_STARTED = 'FETCH_GENRES_STARTED';
export const FETCH_GENRES_COMPLETED = 'FETCH_GENRES_COMPLETED';
export const FETCH_GENRES_FAILED = 'FETCH_GENRES_FAILED';

export const ADD_GENRE_STARTED = 'ADD_GENRE_STARTED';
export const ADD_GENRE_COMPLETED = 'ADD_GENRE_COMPLETED';
export const ADD_GENRE_FAILED = 'ADD_GENRE_FAILED';

export const REMOVE_GENRE_STARTED = 'REMOVE_GENRE_STARTED';
export const REMOVE_GENRE_COMPLETED = 'REMOVE_GENRE_COMPLETED';
export const REMOVE_GENRE_FAILED = 'REMOVE_GENRE_FAILED';