export const FETCH_MOVIES_STARTED = 'FETCH_MOVIES_STARTED';
export const FETCH_MOVIES_COMPLETED = 'FETCH_MOVIES_COMPLETED';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';

export const ADD_MOVIE_STARTED = 'ADD_MOVIE_STARTED';
export const ADD_MOVIE_COMPLETED = 'ADD_MOVIE_COMPLETED';
export const ADD_MOVIE_FAILED = 'ADD_MOVIE_FAILED';

export const REMOVE_MOVIE_STARTED = 'REMOVE_MOVIE_STARTED';
export const REMOVE_MOVIE_COMPLETED = 'REMOVE_MOVIE_COMPLETED';
export const REMOVE_MOVIE_FAILED = 'REMOVE_MOVIE_FAILED';