export const FETCH_MOVIE_PRODUCERS_STARTED = 'FETCH_MOVIE_PRODUCERS_STARTED';
export const FETCH_MOVIE_PRODUCERS_COMPLETED = 'FETCH_MOVIE_PRODUCERS_COMPLETED';
export const FETCH_MOVIE_PRODUCERS_FAILED = 'FETCH_MOVIE_PRODUCERS_FAILED';

export const ADD_MOVIE_PRODUCER_STARTED = 'ADD_MOVIE_PRODUCER_STARTED';
export const ADD_MOVIE_PRODUCER_COMPLETED = 'ADD_MOVIE_PRODUCER_COMPLETED';
export const ADD_MOVIE_PRODUCER_FAILED = 'ADD_MOVIE_PRODUCER_FAILED';

export const REMOVE_MOVIE_PRODUCER_STARTED = 'REMOVE_MOVIE_PRODUCER_STARTED';
export const REMOVE_MOVIE_PRODUCER_COMPLETED = 'REMOVE_MOVIE_PRODUCER_COMPLETED';
export const REMOVE_MOVIE_PRODUCER_FAILED = 'REMOVE_MOVIE_PRODUCER_FAILED';