export const FETCH_SEARCH_SERIES_STARTED = 'FETCH_ALL_SERIES_STARTED';
export const FETCH_SEARCH_SERIES_COMPLETED = 'FETCH_ALL_SERIES_COMPLETED';
export const FETCH_SEARCH_SERIES_FAILED = 'FETCH_ALL_SERIES_FAILED';