export const FETCH_SEARCH_MOVIES_STARTED = 'FETCH_ALL_MOVIES_STARTED';
export const FETCH_SEARCH_MOVIES_COMPLETED = 'FETCH_ALL_MOVIES_COMPLETED';
export const FETCH_SEARCH_MOVIES_FAILED = 'FETCH_ALL_MOVIES_FAILED';