export const FETCH_SEARCH_VIDEOGAMES_STARTED = 'FETCH_ALL_VIDEOGAMES_STARTED';
export const FETCH_SEARCH_VIDEOGAMES_COMPLETED = 'FETCH_ALL_VIDEOGAMES_COMPLETED';
export const FETCH_SEARCH_VIDEOGAMES_FAILED = 'FETCH_ALL_VIDEOGAMES_FAILED';