export const FETCH_SERIES_STARTED = 'FETCH_SERIES_STARTED';
export const FETCH_SERIES_COMPLETED = 'FETCH_SERIES_COMPLETED';
export const FETCH_SERIES_FAILED = 'FETCH_SERIES_FAILED';

export const ADD_SERIE_STARTED = 'ADD_SERIE_STARTED';
export const ADD_SERIE_COMPLETED = 'ADD_SERIE_COMPLETED';
export const ADD_SERIE_FAILED = 'ADD_SERIE_FAILED';

export const REMOVE_SERIE_STARTED = 'REMOVE_SERIE_STARTED';
export const REMOVE_SERIE_COMPLETED = 'REMOVE_SERIE_COMPLETED';
export const REMOVE_SERIE_FAILED = 'REMOVE_SERIE_FAILED';