export const FETCH_VIDEOGAMES_STARTED = 'FETCH_VIDEOGAMES_STARTED';
export const FETCH_VIDEOGAMES_COMPLETED = 'FETCH_VIDEOGAMES_COMPLETED';
export const FETCH_VIDEOGAMES_FAILED = 'FETCH_VIDEOGAMES_FAILED';

export const ADD_VIDEOGAME_STARTED = 'ADD_VIDEOGAME_STARTED';
export const ADD_VIDEOGAME_COMPLETED = 'ADD_VIDEOGAME_COMPLETED';
export const ADD_VIDEOGAME_FAILED = 'ADD_VIDEOGAME_FAILED';

export const REMOVE_VIDEOGAME_STARTED = 'REMOVE_VIDEOGAME_STARTED';
export const REMOVE_VIDEOGAME_COMPLETED = 'REMOVE_VIDEOGAME_COMPLETED';
export const REMOVE_VIDEOGAME_FAILED = 'REMOVE_VIDEOGAME_FAILED';